name = "barber-shop"  # Как в Cloudflare Dashboard
compatibility_date = "2024-09-23"

# KV хранилище
kv_namespaces = [
  { binding = "BARBERSHOP_KV", id = "e20bde6901ab4f5e9fe2128b66bd4128" }
]

[site]
bucket = ".open-next/cloudflare"