name = "barber-shop" # Или "dzyadushka-ru", как у тебя назван проект в CF
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"] # <--- ВОТ ЭТО ГЛАВНОЕ ИСПРАВЛЕНИЕ

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BARBERSHOP_KV"
id = "e20bde6901ab4f5e9fe2128b66bd4128"